# Generated by Django 4.2.17 on 2025-01-01 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_adimage_delete_user_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Ad',
        ),
        migrations.RenameIndex(
            model_name='ad',
            new_name='ads_ad_created_131ac9_idx',
            old_name='ads_adverti_created_28f1a5_idx',
        ),
    ]
