# Generated by Django 4.2.17 on 2025-01-01 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_advertisement_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=3),
        ),
    ]
