# Generated by Django 4.2.17 on 2025-01-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_active_alter_ad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='active',
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IAC', 'Inactive'), ('PD', 'Pending')], default='IAC', max_length=3),
        ),
    ]
