# Generated by Django 4.2.17 on 2025-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ad_active_alter_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, unique_for_date='publish'),
        ),
    ]
